from src.Question import Question

questions = Question()

questions.top_10_movies_in_2_years()
questions.series_released_since_2020_and_rating_higher_than_8()
questions.top_10_directors_by_average_rating()
questions.most_frequent_co_actors()
questions.most_common_professions()
questions.top_5_movies_by_votes_per_year()
questions.compare_movie_rating_to_genre_mean_by_year()
questions.top_5_writers_between_1939_and_1945_and_the_most_popular_genre_by_them()
questions.top_5_dead_directors_by_the_highest_overall_average_rating()

questions.top_20_actors_most_episodes()
questions.actors_with_worst_ratings()
questions.actors_most_improved_rating()
questions.actors_most_genres()
questions.directors_most_actors()
questions.actors_most_directors()

questions.series_with_most_episodes()
questions.shortest_movies()
questions.actors_with_biggest_rating_difference()
questions.movies_with_most_adaptations()
questions.people_with_longest_careers()
questions.actors_in_most_animated_movies()

questions.top_5_writers_between_1939_and_1945_and_the_most_popular_genre_by_them()
questions.top_5_dead_directors_by_the_highest_overall_average_rating()
questions.top_5_movies_by_votes_per_year()
questions.youngest_actors_and_actresses()
questions.movies_produced_each_year_and_average_runtime()
questions.average_rating_of_drama_movies_in_ukraine_and_usa()
